### ISSUE TITLE
Error running nf-nomad@latest

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nf-nomad#54]
## Error
```
Jul-03 09:39:27.595 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-nomad@latest
Jul-03 09:39:28.113 [main] ERROR nextflow.cli.Launcher - @unknown
com.github.zafarkhaja.semver.UnexpectedCharacterException: null
        at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
        at com.github.zafarkhaja.semver.VersionParser.digits(VersionParser.java:448)
        at com.github.zafarkhaja.semver.VersionParser.numericIdentifier(VersionParser.java:408)
        at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:285)
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
        at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
        at org.pf4j.DefaultVersionManager.compareVersions(DefaultVersionManager.java:47)
        at nextflow.plugin.CustomVersionManager.compareVersions(CustomVersionManager.groovy:60)
        at org.pf4j.update.UpdateManager.findReleaseForPlugin(UpdateManager.java:330)
        at org.pf4j.update.UpdateManager.downloadPlugin(UpdateManager.java:268)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
        at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:82)
        at nextflow.plugin.PluginUpdater$_safeDownloadPlugin_lambda2.doCall(PluginUpdater.groovy:235)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:236)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:75)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:176)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:437)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
        at nextflow.plugin.PluginUpdater.safeDownloadPlugin(PluginUpdater.groovy:237)
        at nextflow.plugin.PluginUpdater.download0(PluginUpdater.groovy:215)
        at nextflow.plugin.PluginUpdater.access$0(PluginUpdater.groovy)
        at nextflow.plugin.PluginUpdater$_safeDownload_closure3.doCall(PluginUpdater.groovy:298)
        at nextflow.plugin.PluginUpdater$_safeDownload_closure3.call(PluginUpdater.groovy)
        at nextflow.file.FileMutex.lock(FileMutex.groovy:106)
        at nextflow.plugin.PluginUpdater.safeDownload(PluginUpdater.groovy:298)
        at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:333)
        at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:198)
        at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:145)
        at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:335)
        at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:340)
        at nextflow.plugin.PluginsFacade.load(PluginsFacade.groovy:239)
        at nextflow.plugin.Plugins.load(Plugins.groovy:52)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:338)
        at nextflow.cli.Launcher.run(Launcher.groovy:503)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

## Command
```
nextflow run hello -c nomad.config
```

## Config
```
plugins {
     id 'nf-nomad@latest'
}
 
process {
     executor = "nomad"
}
 
nomad {
 
     client {
         address = "redacted"
         token   = "redacted"
 

     }
 
     jobs {
         deleteOnCompletion = false
         namespace = "nextflow"

volumes = [
   { type "csi" name "nf_scratch_volume" path "/scratch" },
   { type "csi" name "nf_reference_volume" path "/references" }
]
 

     }
 
}
```

**Comment by jagedn** [comment]
`latest` is a "fake" version we build and install locally with the `./gradlew unzipPlugin -P version=latest` command

did you execute the command?

**Comment by matthdsm** [comment]
no, I tried to pull the "latest" version from the nextflow registry.
When pinning the version to 0.1.1 and downloading the release artifact it works perfectly.
